
package view;



import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class From extends javax.swing.JFrame {

    /**
     * Creates new form From
     */
    public From() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGender = new javax.swing.ButtonGroup();
        panBackground = new javax.swing.JPanel();
        panHeader = new javax.swing.JPanel();
        lvlHeader = new javax.swing.JLabel();
        lvlName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lvlContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lvlEmail = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lvlDOB = new javax.swing.JLabel();
        lvlGender = new javax.swing.JLabel();
        lvlHobby = new javax.swing.JLabel();
        jRadioMale = new javax.swing.JRadioButton();
        jRadioFemale = new javax.swing.JRadioButton();
        jRadioOther = new javax.swing.JRadioButton();
        jCheckBoxRead = new javax.swing.JCheckBox();
        jCheckBoxGame = new javax.swing.JCheckBox();
        jCheckBoxTravel = new javax.swing.JCheckBox();
        lvlSub = new javax.swing.JLabel();
        jComboBoxSub = new javax.swing.JComboBox<>();
        jDateDOB = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panBackground.setBackground(new java.awt.Color(255, 255, 255));
        panBackground.setPreferredSize(new java.awt.Dimension(700, 700));

        panHeader.setBackground(new java.awt.Color(104, 213, 213));

        lvlHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lvlHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlHeader.setText("Data Entry Form");

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lvlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lvlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        lvlName.setText("Name");
        lvlName.setPreferredSize(new java.awt.Dimension(40, 20));

        lvlContact.setText("Contact");
        lvlContact.setPreferredSize(new java.awt.Dimension(40, 20));

        lvlEmail.setText("Email");
        lvlEmail.setPreferredSize(new java.awt.Dimension(40, 20));

        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        btnReset.setText("Reset");

        lvlDOB.setText("DOB");
        lvlDOB.setPreferredSize(new java.awt.Dimension(40, 20));

        lvlGender.setText("Gender");
        lvlGender.setPreferredSize(new java.awt.Dimension(40, 20));

        lvlHobby.setText("Hobby");
        lvlHobby.setPreferredSize(new java.awt.Dimension(40, 20));

        buttonGender.add(jRadioMale);
        jRadioMale.setText("Male");

        buttonGender.add(jRadioFemale);
        jRadioFemale.setText("Female");

        buttonGender.add(jRadioOther);
        jRadioOther.setText("Other");

        jCheckBoxRead.setText("Reading");

        jCheckBoxGame.setText("Gaming");

        jCheckBoxTravel.setText("Travaling");

        lvlSub.setText("Subject");
        lvlSub.setPreferredSize(new java.awt.Dimension(40, 20));

        jComboBoxSub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select--", "HTML", "JavaScript", "MySql", "Php", "Java", " " }));

        javax.swing.GroupLayout panBackgroundLayout = new javax.swing.GroupLayout(panBackground);
        panBackground.setLayout(panBackgroundLayout);
        panBackgroundLayout.setHorizontalGroup(
            panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panBackgroundLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panBackgroundLayout.createSequentialGroup()
                                .addComponent(lvlName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panBackgroundLayout.createSequentialGroup()
                                .addComponent(lvlContact, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panBackgroundLayout.createSequentialGroup()
                                .addComponent(btnSubmit)
                                .addGap(158, 158, 158)
                                .addComponent(btnReset))
                            .addGroup(panBackgroundLayout.createSequentialGroup()
                                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panBackgroundLayout.createSequentialGroup()
                                        .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lvlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lvlDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lvlHobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(45, 45, 45))
                                    .addGroup(panBackgroundLayout.createSequentialGroup()
                                        .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lvlSub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lvlGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(37, 37, 37)))
                                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addGroup(panBackgroundLayout.createSequentialGroup()
                                        .addComponent(jRadioMale)
                                        .addGap(60, 60, 60)
                                        .addComponent(jRadioFemale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                        .addComponent(jRadioOther))
                                    .addGroup(panBackgroundLayout.createSequentialGroup()
                                        .addComponent(jCheckBoxRead)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxGame)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxTravel))
                                    .addComponent(jDateDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxSub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 226, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panBackgroundLayout.setVerticalGroup(
            panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lvlDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioMale)
                    .addComponent(jRadioFemale)
                    .addComponent(jRadioOther))
                .addGap(18, 18, 18)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlHobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxRead)
                    .addComponent(jCheckBoxGame)
                    .addComponent(jCheckBoxTravel))
                .addGap(18, 18, 18)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnReset))
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String getGender(){
        String gender = "";
        if (jRadioMale.isSelected()) {
            gender = "Male";
        } else if(jRadioFemale.isSelected()){
            gender = "Female";
        } else if(jRadioOther.isSelected()){
            gender="Other";
        } else {
            gender ="Not Selected";
        }
        return gender;
    }
    private String getHobby(){
        List<String> hobby = new ArrayList<>();
        if (jCheckBoxRead.isSelected()) {
            hobby.add(jCheckBoxRead.getText());
        }
        if (jCheckBoxGame.isSelected()) {
            hobby.add(jCheckBoxGame.getText());
        }
        if (jCheckBoxTravel.isSelected()) {
            hobby.add(jCheckBoxTravel.getText());
        }
        
        if (!(hobby.isEmpty())) {
//            for (int i = 0; i < hobby.size(); i++) {
//                String writeHobby = hobby.get(i)+",";
//                
//            }
//            for(String wHobby:hobby){
//                String hlist += wHobby;
//            }
            return hobby.toString();
        } else {
            return "Not Selected";
        }
        
        
        
    }
    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        PrintWriter pw = null;
        try {
            // TODO add your handling code here:
            String name = txtName.getText().trim();
            String contact = txtContact.getText().trim();
            String email = txtEmail.getText().trim();
            String gender = getGender();
            String hobby = getHobby();
            
            String subject = jComboBoxSub.getSelectedItem().toString();
            String dateOfBirth =jDateDOB.getDate().toString();
            
// Write data to file
            pw = new PrintWriter("output.txt");
            pw.print("Name: "+name+"\n");
            pw.print("Contact: "+contact+"\n");
            pw.print("Email: "+email+"\n");
            pw.print("Gender: "+gender+"\n");
            pw.print("Hobby: "+hobby+"\n");
            pw.print("Subject: "+subject+"\n");
            pw.print("Date Of Birth: "+dateOfBirth);
//            pw.print("Name: "+name+"\n");
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(From.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            pw.close();
            JOptionPane.showMessageDialog(rootPane, "Data saved");
        }
                
    }//GEN-LAST:event_btnSubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new From().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGender;
    private javax.swing.JCheckBox jCheckBoxGame;
    private javax.swing.JCheckBox jCheckBoxRead;
    private javax.swing.JCheckBox jCheckBoxTravel;
    private javax.swing.JComboBox<String> jComboBoxSub;
    private com.toedter.calendar.JDateChooser jDateDOB;
    private javax.swing.JRadioButton jRadioFemale;
    private javax.swing.JRadioButton jRadioMale;
    private javax.swing.JRadioButton jRadioOther;
    private javax.swing.JLabel lvlContact;
    private javax.swing.JLabel lvlDOB;
    private javax.swing.JLabel lvlEmail;
    private javax.swing.JLabel lvlGender;
    private javax.swing.JLabel lvlHeader;
    private javax.swing.JLabel lvlHobby;
    private javax.swing.JLabel lvlName;
    private javax.swing.JLabel lvlSub;
    private javax.swing.JPanel panBackground;
    private javax.swing.JPanel panHeader;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
